services:
  classifieds-api:
    container_name: classifieds-api
    image: classifieds-api
    environment:
      NODE_ENV: ${NODE_ENV}
      PORT: ${PORT}
      DATABASE_URL: ${DATABASE_URL}
      ALLOWED_ORIGINS: ${ALLOWED_ORIGINS}
      JWT_SECRET: ${JWT_SECRET}
      JWT_EXPIRES_IN: ${JWT_EXPIRES_IN}
      SWAGGER_ENABLED: ${SWAGGER_ENABLED}
      ADMIN_EMAIL: ${ADMIN_EMAIL}
      ADMIN_PASSWORD: ${ADMIN_PASSWORD}
    ports:
      - ${PORT}:${PORT}
    depends_on:
      - classifieds-db
    networks:
      - classifieds-network

  classifieds-db:
    container_name: classifieds-db
    image: postgres:14.0-alpine
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - classifieds-db-data:/var/lib/postgresql/data
    networks:
      - classifieds-network

volumes:
  classifieds-db-data:
networks:
  classifieds-network:
